### ISSUE TITLE
1.20.X version crashes on launch on 1.20 - 1.20.4

### ISSUE THREAD

**Issue by PalladiumHexafluoride** [cheyao/animated-logo#2]
Just like the title says game crashes instantly, fabric says Animated loading screen wants java 21 when running 1.20 - 1.20.4 versions of the game which use java 17

**Comment by cheyao** [comment]
Should be fixed now, just pushed a new jar to modrinth https://modrinth.com/mod/animated-loading-screen/version/RJcpyvWu

Thanks for the bug report!

**Comment by PalladiumHexafluoride** [comment]
Thanks for the quick reply and fix! But it's unfortunately still not working, different error now... =(
